### PR TITLE
CDateTime: Fix interference of text editing and opening picker

### LINKED ISSUE #593: CDateTime does not correctly display selected date when using dropdown after typing a single digit
Using a CDateTime configured for date selection like this:

```
CDateTime cDateTime = new CDateTime(content, CDT.BORDER | CDT.DROP_DOWN | CDT.DATE_MEDIUM);
cDateTime.addSelectionListener(new SelectionListener() {
   @Override
   public void widgetSelected(SelectionEvent e) {
      System.out.println(cDateTime.getSelection());
   }

   @Override
   public void widgetDefaultSelected(SelectionEvent e) {
   }
});
```

- Move focus into the widget, type a single digit "1" --> widget shows the first of month, selection listener gets the current date.
- Open dropdown, select another date by clicking on it (or any other way) --> drop down closes, selection listener gets the selected date, but widget still shows first of month.

### PR DESCRIPTION
**Pull request by christianmichaelis**
fixes https://github.com/eclipse/nebula/issues/593

### CODE REVIEW

**Comment by merks** [comment]
In order to be able to merge your pull request we need you to complete the Eclipse Contribution Agreement, ECA.  These instructions are quite helpful/detailed:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#setting-up-your-eclipse-and-github-account

**Comment by christianmichaelis** [comment]
I just tried to fix the ECA problem. As I used another Email for my Eclipse account, I put my GitHub username in the Eclipse profile. Is this sufficient? How do I re-trigger the check?

**Comment by merks** [comment]
I think it will be okay:

image

But I'm not sure why it's taking so long to update the status here...

**Comment by merks** [comment]
@lcaron 

It looks safe to me, but I don't have deep knowledge...

**Comment by lcaron** [comment]
PR merge. Thank you @christianmichaelis for this bugfix and @merks for your support.

**Pull request merged**
