### PR TITLE
Bug 541345 - Richtext cells calculate wrong height

### PR DESCRIPTION
**Pull request by fipro78**
Fix for issue #27

### CODE REVIEW

**Comment by wimjongman** [comment]
ok to test

**Comment by wimjongman** [comment]
Dirk please set your github user in your eclipse profile. Then you have push access to the repo.

**Comment by wimjongman** [comment]
retest this please

**Comment by fipro78** [comment]
Why? What did you change?

**Comment by wimjongman** [comment]
retest this please is a command to jenkins. Jenkins will build it again after a failure.
ok to test is also a jenkins command [1]

[1] https://wiki.eclipse.org/Nebula/Contributions#Building

**Comment by wimjongman** [comment]
Dirk you also need to bump the version number in the category: https://github.com/eclipse/nebula/blob/master/releng/org.eclipse.nebula.updatesite/category.xml

**Comment by fipro78** [comment]
Hi Wim, I updated the category.xml ... hope everything works now

**Comment by fipro78** [comment]
Hi Wim, I have entered my GitHub username in the Eclipse account settings. But I am still not allowed to merge. Anything else I need to do?

**Comment by wimjongman** [comment]
You probably need to wait a little bit. Please check again your eclipse profile. If it still fails ask the webmeisters.

**Comment by wimjongman** [comment]
https://github.com/orgs/eclipse/people?utf8=%E2%9C%93&query=fipro78

**Comment by fipro78** [comment]
Haven't seen the organization invitation ... now it works ... thanks!

**Pull request merged**
