### PR TITLE
Issue #218 - GeoMap - Zoom listener fired before MapPosition has been

### LINKED ISSUE #218: GeoMap - Zoom listener fired before MapPosition has been updated
In `GeoMapUtil.zoomOut`, `geoMap.setZoom` is called, which updates the zoom level and then calls `fireZoomChanged()`, which causes the listeners to respond to a change in the zoom.

The problem is that the map position is only updated in `GeoMapUtil.zoomOut` after the `geoMap.setZoom` call - which means any listeners responding to the zoom change will be using an outdated map position.

I think in `zoomIn` & `zoomOut` the statements should simply be switched in order.

### PR DESCRIPTION
**Pull request by JackPGreen**
Signed-off-by: JackPGreen <JackPGreen@Gmail.com>

### CODE REVIEW

**Comment by wimjongman** [comment]
Jenkins, ok to test.

**Comment by wimjongman** [comment]
The build is failing Jack. It looks like you have removed the Point import?

**Comment by JackPGreen** [comment]
Hi, I think I've resolved this. Apologies, my first time submitting to Eclipse.

**Comment by wimjongman** [comment]
No worries Jack, I hope it will be the first of many.

It is a little hard to review the changes because you also made unrelated changes: https://github.com/eclipse/nebula/pull/221/files?diff=unified&w=1

Can you please test the changes by importing from this update site:
https://ci.eclipse.org/nebula/job/nebula.stable.github/272/artifact/releng/org.eclipse.nebula.updatesite/target/repository/

**Review by lcaron — APPROVED** [review]
Review done and approved

**Pull request merged**
