### PR TITLE
Bug 551779 - LED Display Widget

### PR DESCRIPTION
**Pull request by lcaron**

### CODE REVIEW

**Comment by fipro78** [comment]
Just a small question. Do you really want to still use EPLv1 or should we think about using EPLv2 nowadays?

**Comment by lcaron** [comment]
> 
> 
> Just a small question. Do you really want to still use EPLv1 or should we think about using EPLv2 nowadays?

Sorry Dirk for my late answer,
Well I copied/pasted the licence information, and after digging all widgets are under EPLv2.
What do you think about opening a bug to migrate all components to EPLv2 ?
What are the impact of such a change ?
@wimjongman what is your opinion ?

**Comment by fipro78** [comment]
I need to check with the foundation if we can simply update to EPLv2 or if we need some additional steps. Actually I think updating to EPLv2 should be the right direction.

**Comment by lcaron** [comment]
> 
> 
> I need to check with the foundation if we can simply update to EPLv2 or if we need some additional steps. Actually I think updating to EPLv2 should be the right direction.

Ok thank you !

**Comment by wimjongman** [comment]
We can just update the headers, see the FAQ. I will make a notice in the mailing list that we are switching.

https://www.eclipse.org/legal/epl-2.0/faq.php

**Pull request merged**
