### PR TITLE
Add "Filtered" in red to XViewer when list is filtered.

### LINKED ISSUE #432: XViewer Widget doesn't notify when it's filtered
Changed the XViewer Widget label at the bottom to display keyword "Filtered", in red, when list is filtered through input box or filtering selected columns.

### PR DESCRIPTION
**Pull request by ghost**
Made changes to the XViewer. It now displays the word "Filtered" in red when user filters through input box or right clicking and selecting filter column.

### CODE REVIEW

**Comment by wimjongman** [comment]
> Can one of the admins verify this patch?

ok to test.

**Comment by wimjongman** [comment]
@hugotrejo2 please file an issue for this that describes what you are trying to solve.

**Comment by ghost** [comment]
> @hugotrejo2 please file an issue for this that describes what you are trying to solve.

@wimjongman are you referring to a bug on gitub or on Bugzilla? I already created one on Bugzilla.

**Comment by wimjongman** [comment]
In GitHub. We don't use bz for this project.

**Comment by ghost** [comment]
> In GitHub. We don't use bz for this project.
I added bug #432

**Review by dondunne — APPROVED** [review]

**Pull request merged**
