### PR TITLE
Bug 566603: The text in Text widget may be displayed in 'prompt' mode.

### PR DESCRIPTION
**Pull request by dariusz-michura**
I know that code contains lot of duplications. I will try to resolve them later.

### CODE REVIEW

**Comment by dariusz-michura** [comment]
Bugzilla reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=566603

**Review by wimjongman — COMMENTED** [review]
Looks good, Dariusz. Thanks! You said you were going to resolve duplicate code? Wait to merge?

**Review by lcaron — COMMENTED** [review]
Ok for me

**Comment by dariusz-michura** [comment]
> Looks good, Dariusz. Thanks! You said you were going to resolve duplicate code? Wait to merge?

I am sorry. Not enough time to do that. I will report another bug and patch it there.

**Comment by wimjongman** [comment]
Thanks, Dariusz!  Please complete the dup code removal when you have time.

**Comment by lcaron** [comment]
Dariusz, do you need some help ? Maybe we can merge and clean the code after ?

**Comment by dariusz-michura** [comment]
Hi lcaron. As I can see the fix has been already merged. I will clean up the code in separate bug.

**Comment by lcaron** [comment]
Hi Dariusz

Thank you for your feedback : can you please close the bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=566603 ?

Feel free to ask if you need help,

Laurent

**Pull request merged**
