### PR TITLE
Issue #241 - GeoMap - Specify a Minimum Zoom Level

### PR DESCRIPTION
**Pull request by JackPGreen**
Signed-off-by: JackPGreen <JackPGreen@Gmail.com>

### CODE REVIEW

**Comment by wimjongman** [comment]
add to whitelist

**Comment by wimjongman** [comment]
Jack there are some issues with the PR. Can you take a look?

**Comment by lcaron** [comment]
There is a conflict on GeoMapUtil. @JackPGreen can you resolve it and push again please ?

**Comment by lcaron** [comment]
There is a conflict on GeoMapUtil. @JackPGreen can you resolve it and push again please ?

**Comment by lcaron** [comment]
I've applied the changes of this PR in a new PR (https://github.com/eclipse/nebula/pull/298)

**Pull request closed without merging**
