### PR TITLE
Added logic to handle when commands have multiple values. Also fixed an

### PR DESCRIPTION
**Pull request by edward-k-francis**
Added logic to handle when commands have multiple values. Also fixed an issue with Bezier cubic 't' relative comparison.

Signed-off-by: Francis,Edward <edward.k.francis@gmail.com>

### CODE REVIEW

**Comment by edward-k-francis** [comment]
@lcaron, this one is better!

**Comment by edward-k-francis** [comment]
@wimjongman and @lcaron was this one going to get merged?

**Comment by wimjongman** [comment]
Thanks!  Apologies for the delay, Edward. I lost track.

**Comment by lcaron** [comment]
Good job, Edwards, congratulations !

**Pull request merged**
