### PR TITLE
Re-normalize line-endings in git of all files to Linux style ("\n")

### PR DESCRIPTION
**Pull request by HannesWell**
Some ASCII-files were checked-in into git having windows style line endings (\r\n). This is in general not wanted because it can cause modified files without any difference in git-staging.

To re-normalize line endings of all files use the following command (including dot):
`git add --renormalize .`

### CODE REVIEW

**Comment by HannesWell** [comment]
Since there are a lot of files with many lines involved I wonder if this is really wanted or if windows line-endings are even desired.
At least it will make the git-blame useless for all affected file.

**Comment by lcaron** [comment]
Thank you hannes for your contribution.
@wimjongman what do you think about merging this PR ?

**Comment by wimjongman** [comment]
Yes, let's go.

**Comment by lcaron** [comment]
PR Merged. Thank you @HannesWell for this nice contribution

**Comment by HannesWell** [comment]
You are welcome and thank you for reviewing. :)

**Pull request merged**
