### PR TITLE
Hard-coded margins in preference window

### PR DESCRIPTION
**Pull request by vogella**
The Apply and Close buttons should not have hard-code marings to zero.

### CODE REVIEW

**Comment by vogella** [comment]
PLEASE DO NOT MERGE, ALSO AFFECTS THE BUTTON CONTAINER. NEEDS MORE WORK:

**Comment by vogella** [comment]
Ready for review.

**Comment by vogella** [comment]
@laeubi how can I remove the "Draft" flag?

**Review by lcaron — APPROVED** [review]
Ok to merge

**Comment by lcaron** [comment]
Pr Merged, thank you @vogella !

**Pull request merged**
