### PR TITLE
Bug 511353 - Support render link and manage link interaction in RichText

### PR DESCRIPTION
**Pull request by lcaron**
When a user add an hyperlink (anchor < a href="..." >) the link is underline, and a click on it opens the default browser with the URL.

### CODE REVIEW

**Review by fipro78 — COMMENTED** [review]
I need to check your proposal in more detail. The TagProcessingState class for example is completely changed, so to see the real changes is not possible. Probably a line ending issue.
And why is there an anchor stack? Can anchors be wrapped with other anchors that would need to have a stack?

Personally I am not sure if the implementation covers all aspects. What if there is a line break? Does the area for the hover processing take care of that? And what if the link should be used for internal references? The current implementation only supports to directly open an external browser.

I actually thought of a more general "action item" implementation that can be extended e.g. for opening a browser or similar.

Please do not merge until I have found the time to review in more detail!

**Comment by lcaron** [comment]
> I need to check your proposal in more detail. The TagProcessingState class for example is completely changed, so to see the real changes is not possible. Probably a line ending issue.

Sorry of that. In this class I just added the anchorStack + a push method + a poll method

> And why is there an anchor stack? Can anchors be wrapped with other anchors that would need to have a stack?
> 
Can you explain please ?

> Personally I am not sure if the implementation covers all aspects. What if there is a line break? Does the area for the hover processing take care of that? 

No I forgot this case. I'm gonna check it

> And what if the link should be used for internal references? The current implementation only supports to directly open an external browser.
> 

True, I just worked on the described use-case.

> I actually thought of a more general "action item" implementation that can be extended e.g. for opening a browser or similar.
> 

Good idea, even if I have no idea how to implement it : a list of action (first hyperlink=action and so on) ? An attribute ? Or a map URL/Action ? (for instance if href ="refresh" call the method refreshScreen() associated to this url) ?

> Please do not merge until I have found the time to review in more detail!

Of course :)
Thanks for your time.

**Comment by fipro78** [comment]
> > I need to check your proposal in more detail. The TagProcessingState class for example is completely changed, so to see the real changes is not possible. Probably a line ending issue.
> 
> Sorry of that. In this class I just added the anchorStack + a push method + a poll method
> 
> > And why is there an anchor stack? Can anchors be wrapped with other anchors that would need to have a stack?
> 
> Can you explain please ?
> 

Well, I added the stack design to handle nested tags. For example the styling can be nested to first specify a background color and only for a single word a different foreground color. To handle those scenarios a stack needs to be used, as the styles need to be closed in the correct order by still supporting the inheritance of the style setting. Same for the font, if e.g. only a single word should be italic for a sentence in a specific font type.
I don't think such a stack behavior is needed for links or action items, because AFAIK links can not be nested with other links.

> > Personally I am not sure if the implementation covers all aspects. What if there is a line break? Does the area for the hover processing take care of that?
> 
> No I forgot this case. I'm gonna check it
> 

IMHO this is a complicated one. Because a text that can break should support the same action. But then a modified region needs to be set for the rest of the text on the new line.

> > And what if the link should be used for internal references? The current implementation only supports to directly open an external browser.
> 
> True, I just worked on the described use-case.
> 

For the described use case surely enough, and if the region can be determined for the link, this can be adapted later. Just wanted to point out which direction I would like to go here. One use case could be to scroll to a row in a NatTable similar to cross references in a table.

> > I actually thought of a more general "action item" implementation that can be extended e.g. for opening a browser or similar.
> 
> Good idea, even if I have no idea how to implement it : a list of action (first hyperlink=action and so on) ? An attribute ? Or a map URL/Action ? (for instance if href ="refresh" call the method refreshScreen() associated to this url) ?
> 

That actually needs to be defined. Maybe with a prefix in the href attribute that specifies the action. This would even match the HTML spec IIRC. We have a link and the URI defines the type or reference. 

> > Please do not merge until I have found the time to review in more detail!
> 
> Of course :)
> Thanks for your time.

Another possible issue is the integration in other widgets, e.g. JFace viewer and NatTable. Does the hover listener work correctly when integrating the RichTextViewer as viewer in a table?

**Comment by lcaron** [comment]
Thank you for your feedback.
You're totally right, a stack for the Anchor Element is not relevant. I'll change it.

I've dug the problem of URL split into 2 lines (word wrap). I agree : it seems VERY complicated, but I have an idea. I'll try it.

For the configuration issue, I propose your idea : if the URL is http(s)://... the default browser will be opened. if the url is action://XXXX the action "XXXX" will be called.

Finally, I'm gonna check the "hover" possible issue with a viewer. Do you have an example of using RichTextViewer with another widgets ?

Thanx

**Comment by fipro78** [comment]
There is a JFace viewer integration example here: https://github.com/eclipse/nebula/blob/master/widgets/richtext/org.eclipse.nebula.widgets.richtext.example/src/org/eclipse/nebula/widgets/richtext/example/JFaceViewerIntegrationExample.java

And for NatTable I have a dedicated example here:
https://github.com/eclipse/nebula.widgets.nattable/blob/master/org.eclipse.nebula.widgets.nattable.examples/src/org/eclipse/nebula/widgets/nattable/examples/_400_Configuration/_424_NebulaRichTextIntegrationExample.java

My fear is that your modification has a negative effect on the hover feature in NatTable. But I have not verified this. I will need to create an example that includes both.

**Comment by lcaron** [comment]
> 
> 
> There is a JFace viewer integration example here: https://github.com/eclipse/nebula/blob/master/widgets/richtext/org.eclipse.nebula.widgets.richtext.example/src/org/eclipse/nebula/widgets/richtext/example/JFaceViewerIntegrationExample.java
> 
> And for NatTable I have a dedicated example here:
> https://github.com/eclipse/nebula.widgets.nattable/blob/master/org.eclipse.nebula.widgets.nattable.examples/src/org/eclipse/nebula/widgets/nattable/examples/_400_Configuration/_424_NebulaRichTextIntegrationExample.java
> 
> My fear is that your modification has a negative effect on the hover feature in NatTable. But I have not verified this. I will need to create an example that includes both.

I understand, 

Thank you for your time and support. After a sick leave I'm back to work, so I'll have less time.
Just to tell you : No pressure ;)

**Comment by lcaron** [comment]
> Thank you for your time and support. After a sick leave I'm back to work, so I'll have less time.
> Just to tell you : No pressure ;)

Hi Dirk
Thank you for pointing the problems. You're totally right, this feature leads to unsolvable issues.
If you agree, I propose to mark this bug as "won't fix"

What do you think ?

**Comment by fipro78** [comment]
Not sure if everything is unsolvable. But it definitely has a higher complexity and several side effects that need to be tested. From my point of view it can stay open and I will look after it when I have more time. At least the bugzilla ticket. 

You can close this pr if you think it is not the right direction.

**Comment by lcaron** [comment]
Hi Dirk
Thank you for your feedback. Well I did not think it is unsolvable, but has you noticed it is much more complex than I expected and I think that my approach is going to a dead end.

I'm gonna close this PR but leave the bug open.

Have a nice evening,

Laurent

**Pull request closed without merging**
