### PR TITLE
Update SvgLoader.java

### PR DESCRIPTION
**Pull request by edward-k-francis**
Added logic to handle when commands have multiple values when parsing the path of an svg file.

### CODE REVIEW

**Comment by wimjongman** [comment]
Thanks for the patch, Edward.  Edward, before we can accept your patch, you have to sign the Eclipse Contributor Agreement. Description and instructions are here:

https://www.eclipse.org/legal/ECA.php

@edward-k-francis

**Comment by edward-k-francis** [comment]
@wimjongman I've signed. Thanks.

**Comment by wimjongman** [comment]
jenkins: retest this please

**Comment by wimjongman** [comment]
@edward-k-francis I think you also have to set your github account name in your eclipse profile. Can you confirm that you did this? Sorry for all the hoop-jumping. It is annoying.

**Comment by edward-k-francis** [comment]
Here is my account. It has the GitHub user link in it.

https://accounts.eclipse.org/users/efranciswy4

**Comment by lcaron** [comment]
Edward, your commit has been authored with the following email adresse "Edward.Francis@****.com".
It is the email address associated to your eclipse account ?

**Comment by edward-k-francis** [comment]
That's probably the issue. I've used my personal email for my eclipse and GitHub accounts. This code fix was for something with work so I used my work computer and that puts my work email as the author.

**Comment by edward-k-francis** [comment]
I've changed my email on my eclipse account.

**Comment by lcaron** [comment]
jenkins: retest this please

**Comment by lcaron** [comment]
Weird... Edward can you contact me by mail (laurent dot caron [at] gmail dot com) ?

**Comment by edward-k-francis** [comment]
Looks like the check is failing on the Signed off by not being on all commits.  I might have to just start over again with a new pull request.

**Comment by wimjongman** [comment]
Thanks. There is a discussion here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=558653

**Pull request closed without merging**
