### PR TITLE
Add filter method.

### PR DESCRIPTION
**Pull request by jcommand**
Thank you for the PropertyTable. It would also be great if you could filter the table/tree. I have implemented this. 
Alternatively, setting "final List<PTProperty> properties" to protected would be enough for me. Would be helpful for all package visible varaiblen too.

### CODE REVIEW

**Comment by lcaron** [comment]
Thank you for you PR and your enhancement. 

In order to merge your code, you have to sign the *Eclipse Contributor Agreement*. Please have a look at https://www.eclipse.org/legal/ECA.php

Feel free to ask if you need any help,

Laurent

**Comment by lcaron** [comment]
@jcommand Hi can you please sign the ECA in order to merge this interesting Pull Request ?

FYI the next release of Nebula is planned for June, 20th 

Feel free to ask :)

**Comment by lcaron** [comment]
@jcommand I can not merge this PR because you have to sign the Eclipse Contributor Agreement (look at https://accounts.eclipse.org/user/94713/eca/3.1.0)

Feel free to ask.

**Comment by lcaron** [comment]
@jcommand I can not merge this PR because you have to sign the Eclipse Contributor Agreement (look at https://accounts.eclipse.org/user/94713/eca/3.1.0)

Feel free to ask.

**Comment by lcaron** [comment]
@jcommand I can not merge this PR because you have to sign the Eclipse Contributor Agreement (look at https://accounts.eclipse.org/user/94713/eca/3.1.0)

Feel free to ask.

**Comment by lcaron** [comment]
@jcommand I can not merge this PR because you have to sign the Eclipse Contributor Agreement (look at https://accounts.eclipse.org/user/94713/eca/3.1.0)

Feel free to ask.

**Comment by wimjongman** [comment]
Closing according to no response from the author.

**Pull request closed without merging**
