### PR TITLE
Bug 566682: The prompt text does not disappear when Text widget gathers the focus

### PR DESCRIPTION
**Pull request by dariusz-michura**

### CODE REVIEW

**Comment by dariusz-michura** [comment]
Bugzilla reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=566682

**Comment by wimjongman** [comment]
@dariusz-michura: Thank you for the patch. In order to be able to accept your PR you need to do a couple of things. We need this so to protect the users of Eclipse software for IP infringement.

1. Create and account on eclipse.org
2. Set your github account name in your profile
3. Accept the ECA. You can find it in your eclipse profile page.
4. Signoff your commit. Your commit must have the last line like so:

       Signed-off-by: Darius Michura <your-mail@some.com>

**Comment by wimjongman** [comment]
jenkins: ok to test

**Comment by dariusz-michura** [comment]
@wimjongman It is something wrong with my ECA. For unknown reason it is signed with wrong email address. I already emailed Eclipse for this. Will let you know when I get responded.

**Comment by dariusz-michura** [comment]
@wimjongman My ECA is OK now. All PR checks passed.

**Comment by wimjongman** [comment]
jenkins: add to whitelist

**Comment by wimjongman** [comment]
@dariusz-michura Thanks!!

**Pull request merged**
