### PR TITLE
Bug: 559863 [New Widget] Timeline

### PR DESCRIPTION
**Pull request by Pontesegger**
Initial contribution of the timeline widget

Signed-off-by: Christian Pontesegger <christian.pontesegger@web.de>

### CODE REVIEW

**Comment by wimjongman** [comment]
add to whitelist

**Comment by wimjongman** [comment]
jenkins, ok to test

**Comment by Pontesegger** [comment]
I added pom files already, yet the plugins are not part of the build so far as I did not add it to the master pom

**Comment by wimjongman** [comment]
I see. You can add them to the master pom for now so that we have a complete build.

**Comment by Pontesegger** [comment]
Build looks fine now.
Please have a look at the nebula.incubation.feature/feature.xml - it was empty before my commit, even if there are multiple incubation widgets available.
Further I am not sure about the source plugins and how they are added to the build

**Comment by Pontesegger** [comment]
please wait for a few updates before merging

**Comment by Pontesegger** [comment]
Is this pull request still open for minor changes or shall I wait until the CQ is through?

**Comment by wimjongman** [comment]
Sure go ahead.

**Comment by wimjongman** [comment]
Christian, thanks for creating the example tab. 

Please also provide a snippets project that contains timeline exampes in standalone snippets.

**Comment by wimjongman** [comment]
When I look at the timeline in the example view, I can force a hang by first checking hfill/vfill and then unchecking hfill.

The code will loop on line 95 of DetailFigure where both the  stepSizeInEventTime and factor have the value "Infinity"

image

**Comment by Pontesegger** [comment]
Bug fixed. The widget still does not know about its preferred size, but you now can change flags without the div by 0 problem

**Comment by Pontesegger** [comment]
Snippets added

**Comment by wimjongman** [comment]
Thanks, Mr. Pontesegger. A very nice widget.

**Comment by lcaron** [comment]
Congrats Christian, very nice widget !
And thank you for sharing it and make it part of Nebula ;)

**Pull request merged**
