### PR TITLE
Added FILTERED label when partially filtered

### PR DESCRIPTION
**Pull request by ghost**
A user wanted an indication that the Branch Manager was being filtered, so we added some styled text to the String that displays filter text.

### CODE REVIEW

**Review by lcaron — APPROVED** [review]
Nice Job, thank you very much !

**Comment by ghost** [comment]
> 
> 
> Nice Job, thank you very much !

I went back and noticed I added the fix twice. I need to remove the duplicate code on line 663.

**Review by lcaron — COMMENTED** [review]
Ok for me, good job, congratulations

**Review by dondunne — COMMENTED** [review]
Fix title.  Remove "Improvement[TW15179]: "

**Comment by ghost** [comment]
> 
> 
> Fix title. Remove "Improvement[TW15179]: "
The text has been removed.

**Comment by lcaron** [comment]
@dondunne Is it ok for you ?

**Review by dondunne — COMMENTED** [review]
Yeah, title still doesn't make sense in just an XViewer context.  How about "Add FILTERED label when partially filtered"

**Comment by dondunne** [comment]
> @dondunne Is it ok for you ?

Still testing.  Taking little longer cause I have to learn github, never used before.

**Comment by ghost** [comment]
> 
> 
> > @dondunne Is it ok for you ?
> 
> Still testing. Taking little longer cause I have to learn github, never used before.

We are both learning a few things about github. 😄

**Comment by ghost** [comment]
> 
> 
> Yeah, title still doesn't make sense in just an XViewer context. How about "Add FILTERED label when partially filtered"

I made the change to the title as mentioned above.

**Comment by dondunne** [comment]
Need to make it look like it did before.  Before the change, it was a single line with a common grey-ish background with bold text.  When filtered, the text showed read but the back ground and bold stayed.  Now, background is white and it turns into 2 lines and it's not bold.  Please figure out how to do the same with new StyledText.

**Comment by wimjongman** [comment]
jenkins ok to test

**Comment by dondunne** [comment]
I will review, but out on vacation for week.  Nothing is being held up by
this commit.

**Comment by dondunne** [comment]
Tried to apply the latest patch to test locally, but got this.  Worked on the latest  patch.  

What does that mean?

$ git am -3 /c/Users/b0727536/Desktop/2c196b2f7ee8b217ff633e4760547a2620268409.patch
Applying: Foreground was changed to match the widget grey color. Filter text changed back to one line.
error: sha1 information is lacking or useless (widgets/xviewer/org.eclipse.nebula.widgets.xviewer/src/org/eclipse/nebula/widgets/xviewer/XViewer.java).
error: could not build fake ancestor
hint: Use 'git am --show-current-patch' to see the failed patch
Patch failed at 0001 Foreground was changed to match the widget grey color. Filter text changed back to one line.
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

**Comment by wimjongman** [comment]
> What does that mean?

Donald, you can fetch a pull request as a new branch:

git fetch origin pull/370/head:newbranchfordonald

I got that info from this link: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally

**Pull request closed without merging**
